site_name: Raj Bhattacharjea's Homepage
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  features:
    - navigation.sections

nav:
  - Professional Profile: index.md
  - Other Content:
     - 1D Function Approximation: gelu_approx.md

plugins: []